# Generated by Django 3.0.7 on 2020-06-25 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200625_1701'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projects',
            table='tb_projects',
        ),
    ]
